---

- import_tasks: install_enable.yml
  tags:
    - firewalld-install-enable

- import_tasks: service_setup.yml
  when: service_definitions is defined
  tags:
    - firewalld-service-definitions

- import_tasks: ipset_setup.yml
  when: ipset_definitions is defined
  tags:
    - firewalld-ipset-definitions

- import_tasks: zone_setup.yml
  tags:
    - firewalld-zone-definitions
